version: '3.8'

services:
  clientes-microservice:
    build: ..
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=development
      - DB_HOST=clients-db
      - DB_PORT=5432
      - DB_NAME=clients_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - clients-db
    networks:
      - abc-call-network
      
  clients-db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=clients_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_clientes:/var/lib/postgresql/data 
    networks:
      - abc-call-network

volumes:
  postgres_data_clientes:

networks:
  abc-call-network:
    external: true